#!/usr/bin/env ruby

require 'optparse'
require 'orbacle_server'

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: ./orbacle [options]'

  opts.on('-d DIR', '--dir', 'Directory in which project resides') do |dir|
    options[:dir] = dir
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

cli = OrbacleServer::CommandLineInterface.new
cli.(ARGV[0], options)
