#!/usr/bin/env ruby

require 'optparse'
require 'swistakbot'
require 'sqlite3'

Dir.chdir(__dir__)

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: ./swistakbot [options]'

  opts.on('-d DIR', '--dir', 'Directory in which project resides') do |dir|
    options[:dir] = dir
  end
end.parse!

def index(options)
  dir = options.fetch(:dir)
  Dir.chdir(dir)

  files  = Dir.glob('**/*.rb')
  output = {}

  parser = Swistakbot::ParseFileMethods.new

  files.each do |input_file|
    begin
      # puts "Processing #{input_file}"
      output[input_file] = parser.process_file(File.read(input_file))
    rescue Parser::SyntaxError
      puts "Warning: Skipped #{input_file} because of syntax error"
    end
  end

  File.delete(".swistakbot.db") if File.exists?(".swistakbot.db")
  db = SQLite3::Database.new(".swistakbot.db")
  tables = db.execute <<-SQL
    create table constants (
      scope varchar(255),
      name varchar(255),
      type varchar(255),
      file varchar(255),
      line int
    );
SQL
  
  output.each do |file, result|
    result[:constants].each do |c|
      scope, name, type, opts = c

      db.execute("insert into constants values (?, ?, ?, ?, ?)", [
        scope,
        name,
        type.to_s,
        file,
        opts.fetch(:line)
      ])
    end
  end
end

case ARGV[0]
when 'index' then index(options)
end
